### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by kertul** [sd1337/adminlte-2-react#11]
How to implement login page ?
can someone help me

**Comment by tuliocll** [comment]
Hi, see if this work for you or get you a direction:
https://gist.github.com/tuliocll/f3e59cdcdb4ab904191c6e9189abdde2
![Captura de tela de 2019-06-20 00-25-29](https://user-images.githubusercontent.com/22357579/59816291-eea3da00-92f1-11e9-82a7-3204e262d2fe.png)
I am use Formik and Yup, so you need install:
`npm install formik`
or
`yarn add formik`
and
`npm install yup`
or
`yarn add yup`

**Comment by kertul** [comment]
Thank you, this is very helpful
