### ISSUE TITLE
How to use Navbar?

### ISSUE THREAD

**Issue by himu3355** [sd1337/adminlte-2-react#29]
Please tell me where I place Navbar and their items?

**Comment by filipevl** [comment]
I'm needing too

**Comment by himu3355** [comment]
After a long search, I found a solution.

importing Navbar - 
import { Navbar } from 'adminlte-2-react';
const { Core, Entry, MessageItem, NotificationItem, TaskItem } = Navbar;

Using Navbar and their Items
<AdminLTE>
  <Navbar.Core bg="light" expand="lg">
    <Entry icon="fas-power-off" onClick={props.logout}/>
  </Navbar.Core>
</AdminLTE>
