### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by tadashiando** [sd1337/adminlte-2-react#4]
I have an issue with PureCalendarDay, apparently from airbnb? Locally compiling the project just runs fine, but if I try to deploy on Heroku within a node.js application that error blocks the app. I've read that can be a typo mistake, but I've checked the code and nothing apparently is wrong. :( 2 days looking for...

**Comment by sd1337** [comment]
Hi, there seems to be an issues with the create-react-app configuration. This caused your error. See my post in the other [issue ](https://github.com/sd1337/adminlte-2-react/issues/2#issuecomment-476348358) for a fix. Needs ejecting cra.

**Comment by tadashiando** [comment]
Ejecting CRA and adding the ```option = false``` to TerserPlugin worked. Verified on my end. Thanks!

**Comment by kertul** [comment]
Hi. I got the same problem.
But in this case I use Laravel Mix to build the react app.

After I build into production the website cannot open. and I found an error message on the console.

Please help, I cannot complete my project.

Sorry for bad English
