### ISSUE TITLE
Issue with SideBar

### ISSUE THREAD

**Issue by jasonna2607** [sd1337/adminlte-2-react#8]
Hi, I think there's an issue with the Sidebar component.

It happens when the page is refreshed/redirected the second time.

![sidebar](https://user-images.githubusercontent.com/25816729/59176172-dbbf3600-8b8a-11e9-809f-2f774b9d1fab.PNG)

**Comment by sd1337** [comment]
Looking at your screenshot, I assume that you are having a content height issue? Or is something else wrong? The height issue is related to how adminlte renders full screen (using some jquery code) and it does not work to well with the dynamic DOM generation of react. I thought I've already solved all issues but it seems not so

**Comment by jasonna2607** [comment]
Well I’m not sure about that. It only happens if we re-render the dashboard page the second time (logout then login again) and the content height will back to normal again if we toggle something on the page (e.g open/closing of the inspect element tab of Chrome). Any idea on how to fix this?

**Comment by juanruben** [comment]
Hi. It happens to me that when logout and then login again, the sidebar disappear. If I refresh or resize the window, it renders again. It occurs in any browser

**Comment by jasonna2607** [comment]
@juanruben I kinda solve it by setting the content-wrapper css's min-height to 100vh

**Comment by juanruben** [comment]
@jasonna2607 thanks! really worked in just one line. Hope it is solved in future versions

**Comment by jasonna2607** [comment]
no problem 👍

**Comment by juanruben** [comment]
Hi @jasonna2607. Have you verified if this css trick works in production. For me it is fine in localhost, but in production it appears only if the window is resized forcing to re-render

**Comment by juanruben** [comment]
I make it **!important** and that's it. Thanks anyway

**Comment by jasonna2607** [comment]
Yeap I made it !important
